### ISSUE TITLE
Sign library

### ISSUE THREAD

**Issue by quantumstrings** [YUICompressor-NET/YUICompressor.NET#24]
Hi. 
Can you please sign this nice library it's important for me because I'm going to use this library with another signed with key library which have reference to YUICompressor.NET.

**Comment by freeranger** [comment]
Please see https://github.com/YUICompressor-NET/YUICompressor.NET/issues/1 and  https://github.com/YUICompressor-NET/YUICompressor.NET/issues/16 which provides a solution that should work for you.

**Comment by PureKrome** [comment]
No reply from @quantumstrings - so I'm closing this issue.
