### ISSUE TITLE
Helper function to create and emit  CSS inside an Action method

### ISSUE THREAD

**Issue by weedkiller** [YUICompressor-NET/YUICompressor.NET#25]
Hi, I am trying to build/add a CSS snippet into the view - right in the local `@Section  {...<styles >}` using a simple 
Action link, and help would be great... to create and return something like

`ActionResult GetDynamicCss() {...
.p { height: 210px }
..}`

can you guide me is there a way to do this with this lib, or can we get a helper.

thanks

**Comment by freeranger** [comment]
Hi

This is absolutely nothing to do with the functionality of this library so definitely nothing we would ever provide.
Google is your friend here - it returns results like this : http://stackoverflow.com/questions/2716956/how-to-return-dynamic-css-with-asp-net-mvc

**Comment by freeranger** [comment]
Closed as not an issue with yuicompressor
