### ISSUE TITLE
Getters and Setters with ECMAScript

### ISSUE THREAD

**Issue by RonaldWeng** [YUICompressor-NET/YUICompressor.NET#26]
Hi

We have a issue when trying to run the compression with getters and setters 

`get isMobile() {
            //return true or false
            },`

I see there's a fix for this problem in the yui compressor version 2.4.8

https://github.com/yui/yuicompressor/releases

Is there any plan to upgrade this?

**Comment by PureKrome** [comment]
Can you provide an exact link, please. As in, a link to any commits or patches. Or submit a PR?

**Comment by tsahi** [comment]
I'm also affected by this. the following code produces a "missing : after property id" error:

    var test = {
        get testProperty() {
            return 42;
        }
    }

I don't know how this is fixed in 2.4.8, as I have YUICompressor.NET 2.7.0 and still get this.

**Comment by freeranger** [comment]
Hello

The original poster is referring to the java yuicompressor, not to this port.

I suspect the ecmascript parser isn't handling it rather than the compressor per-se.
Would you like to submit a PR to fix this?

**Comment by tsahi** [comment]
I'm not familiar with your code, so I wouldn't know how to fix it.

**Comment by RonaldWeng** [comment]
Hi Apologies for the late reply, we had other pressing matters to attend to and work seemingly blocked my email from receiving response.

I've relooked at this issue it's as what Tshai said and yes it is the ECMAScript parser does not recoginise Getters and Setters.

**Comment by 84pennies** [comment]
This is also impacting our code as well.  Unable to utilize getters and setters as described here:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects#Defining_getters_and_setters

**Comment by freeranger** [comment]
It is an issue with the ECMAScript parser so you need to raise it there: https://github.com/PureKrome/EcmaScript.NET
Also, feel free to familiarise yourself with that code and submit a PR to that repo to fix it

**Comment by freeranger** [comment]
@PureKrome I think this issue should be closed here since it is not a YUICompressor issue - thoughts?

**Comment by PureKrome** [comment]
Hmm ... maybe lets keep this open because i'll probably need to update the dependency version and then push out a new version here.

Urgh...... Don't even know if I can fix the EcmaScript code unless I have some pretty good links to the fix in the original source :/

**Comment by 84pennies** [comment]
@freeranger I will try and take a look at the code over there but it will be a week or so before I'm able.  For now I've used the Object.defineProperty syntax and it's happy with it.  Thanks for the quick replies and hopefully we can work towards an update to support getters and setters!

**Comment by PureKrome** [comment]
Maybe I can also update the package to .NETStandardBannana or whatever is the recommendation these days.

**Comment by freeranger** [comment]
If the graph you posted here still stands: https://github.com/YUICompressor-NET/YUICompressor.NET/issues/22 then you would be cutting out a wide section of the potential audience since .NETStandard doesn't seem to be available on Windows 7: https://github.com/dotnet/standard/blob/master/docs/versions.md

If you made it target multiple frameworks then we could support .net 2/4/core/standard/whatever is next.

**Comment by PureKrome** [comment]
Fixed in #33 - I feel like the issue might be related to the other ECMAScript repo. If so, ping that repo or we can reopen this issue.
