### ISSUE TITLE
.NET Core compatibility 

### ISSUE THREAD

**Issue by Robar666** [YUICompressor-NET/YUICompressor.NET#31]
Will there be a release version compatible with .Net Core?

**Comment by PureKrome** [comment]
I don't particularly want to because I'm not really working on this repo anymore. I actually haven't really used it for years.

IMO, if someone is going to be looking at requiring .NET Core compatibility then I would suggest that this is a great time to use a better/more-modern package for bundling and minification.

**Comment by freeranger** [comment]
You can use .NET framework packages in .NET Core projects these days - so in that sense, you already have compatibility.

If you mean it should target .NET Standard then there is a dependency on https://github.com/PureKrome/EcmaScript.NET which does not yet have a prod release of a .NET Standard version.

Once that is in place, I'm sure a port would be relatively simple so @Robar666 you could submit a PR.
TBH I am a little surprised someone would want this as there is much more of a focus these days on SPA's and using things like webpack to do bundling and minification.

**Comment by Robar666** [comment]
@freeranger Yes, I wanted to know if it will ever target .NET standard.

I just use this NuGet package for minifying dynamically generated javascript on my server.
I don't use for deployment/bundling/... .

Thanks for your information, guess we'll have to wait for EcmaScript.NET 2.0.0 production release.

**Comment by PureKrome** [comment]
> Thanks for your information, guess we'll have to wait for EcmaScript.NET 2.0.0 production release.

that repo is another one on mind. And that's also in abandonded mode  too... I'm not going to spend energy on it.

**Comment by PureKrome** [comment]
@Robar666 Got some more news for you (even though this might be too late).

We'll plan on updating the project to NS12 & NS20.

Details in #22 

Lets move any questions over to that issue. 🥂

**Comment by Robar666** [comment]
Thanks  @PureKrome , I've just installed the package and everything seems to work. 👍

**Comment by PureKrome** [comment]
@Robar666 Thanks heaps for the feedback - been wondering if anyone has given the package a go/run/test, etc..

much appreciated!
