### ISSUE TITLE
How do I compress ES6 javascripts?

### ISSUE THREAD

**Issue by mrchzh** [YUICompressor-NET/YUICompressor.NET#39]
ES5 ：
JavaScriptCompressor compressor = new JavaScriptCompressor();            
compressor.Encoding = Encoding.UTF8;
string jssource = FileObj.ReadFile(Server.MapPath("/content/js/le.all.js"));
jssource = compressor.Compress(jssource);//min.js
// writefile....
ES6:
 How do I compress ES6 javascripts?
 Thank you. I hope I can answer that.

**Comment by PureKrome** [comment]
Sorry - I'm not too sure. The code for this port was last from 2010/2011. ES6 came out in 2015 so I can't say/confirm/assume that this will know how to compress that.

Sorry.

**Comment by mrchzh** [comment]
> 对不起 - 我不太确定。该端口的代码是2010/2011年的最后一个代码。ES6在2015年问世，所以我不能说/确认/假设这将知道如何压缩它。
> 
> 抱歉。

Thank you very much for your answer!

**Comment by UweKeim** [comment]
We switched to [Nuglify](https://github.com/trullock/NUglify).

**Comment by seedsnj** [comment]
I don't think the underlying v2.0.0 EcmaScript.net library supports or is able to properly process JS code using ES6 features, in particular template string, which it chokes on.  So I will have to look for other complex alternatives.

**Comment by PureKrome** [comment]
> I don't think the underlying v2.0.0 EcmaScript.net library supports or is able to properly process JS code using ES6 features, in particular template string, which it chokes on. So I will have to look for other complex alternatives.

@lichuan80 yep, correct. The [underlying EcmaScript library](https://github.com/PureKrome/EcmaScript.NET) is _also_ archived and not maintained any more.

Good luck with finding a solution

**Comment by GarryLowther** [comment]
I found this: https://javascriptobfuscator.com/downloads.aspx
Has some sample .NET code.
