### ISSUE TITLE
The compressed RGBA color value is incorrect.

### ISSUE THREAD

**Issue by 1123612483** [YUICompressor-NET/YUICompressor.NET#40]
If the RGB value (the first 6 bits of the value) are the same, the RGBA value (8-bit value) is compressed to 5 bits by the compressor. @PureKrome
``` C#
    class Program
    {
        static string CompressCSS()
        {
            var css = @"
                a {
                    background: #F9BE4486;
                    color: #FFFFFF20;
                }";
            var compressor = new CssCompressor();
            // The background value is correct.
            // The expected result of color is #FFFFFF20, and the actual result is #FFF20.
            var compressedCSS = compressor.Compress(css); // a{background:#F9BE4486;color:#FFF20}

            return compressedCSS;
        }
    }
```

**Comment by PureKrome** [comment]
Hi @1123612483 - thanks heaps for the bug report.

Unfortunately, this repo is now more in an archive-not-maintained state. I'll happily review and accept PR's but I don't have the capacity for actually working on this repo.

**Comment by PureKrome** [comment]
Good news @1123612483  -  a new version `3.1.0` is now up on NuGet.org. 

🍰 thanks heaps for the PR!
